### PR TITLE
rtw88: Remove duplicated code

### PR DESCRIPTION
**Pull request by belzerus**
Remove some code blocks that was added by mistake, likely during a merge conflict handling. Also remove some dead code.

### CODE REVIEW

**Review by lwfinger — CHANGES_REQUESTED** [review]
Please leave that "#if 0" block alone. That might be needed again to check  problems.

**Comment by belzerus** [comment]
> Please leave that "#if 0" block alone. That might be needed again to check problems.

Sure! My suggestion in that case is that we add it as a `rtw_dbg` printout instead, is that OK? Also in that case should I add a `RTW_DBG_USB        = 0x00080000,` define for that purpose?

**Comment by lwfinger** [comment]
Please leave it the way it is. It will not be submitted to the kernel, but it is handy to check the results of one of these drivers against the vendor driver.

**Comment by belzerus** [comment]
Ok, got it. Will drop that part and send a v2.

**Comment by dubhater** [comment]
@belzerus Sorry, I forgot about your pull request and implemented the same changes myself.

**Comment by belzerus** [comment]
@dubhater haha, no problem. It was just a simple typo so as long as it was fixed it doesn't matter :) I will close this PR.

**Pull request closed without merging**
