### PR TITLE
Update dkms.conf and Makefile

### PR DESCRIPTION
**Pull request by a5a5aa555oo**

### CODE REVIEW

**Comment by dubhater** [comment]
Applied, thank you!

**Comment by bac0n** [comment]
I think `dkms.conf` is abit problematic. There's `ifeq` statements in the `Makefile` and if any dependency is not met `dkms build` will fail or aleast deviate from `make`. Dynamically create `dkms.conf` from a `.in` template or a simple copy if-not-exist + `.gitignore` will probably work better.

**Comment by a5a5aa555oo** [comment]
I kinda want to delete those ifeq.😆

**Comment by bac0n** [comment]
Maybe do both?

**Pull request closed without merging**
