### PR TITLE
Support building as a Debian DKMS package

### PR DESCRIPTION
**Pull request by RadxaYuntian**
We package this driver as a Debian DKMS package to use in our products. The packaging code can be found [here](https://github.com/radxa-pkg/rtw88) along with the generated deb in GitHub Releases. We mandate packages to be tested by Lintian and treat warning as errors in our CI pipeline. As such, we have found several issues in the code base, which this PR aims to fix.

### CODE REVIEW

**Comment by RadxaYuntian** [comment]
Rebased my branch with the latest driver.

**Comment by RadxaYuntian** [comment]
@lwfinger Can you take a look at this PR?

**Comment by brianwitte** [comment]
@RadxaYuntian -- I am new co-maintainer and will take a look tonight. Thank you for the PR.

**Comment by RadxaYuntian** [comment]
Updated comment message as it was referencing 8723ds fixes before.

**Comment by brianwitte** [comment]
I will need a little more time testing this as I have not run debian in awhile and need to finish setting up my test hardware. I will update you accordingly.

Thanks again for the PR!

**Comment by RadxaYuntian** [comment]
You could check out https://github.com/radxa-pkg/rtw88/tree/main, update the git submodule to pointing to the latest HEAD, and run `make deb`, or use the included GitHub actions to build in their Ubuntu VMs.

**Comment by brianwitte** [comment]
Dug into your build scripts and ran it locally and then looked at the patch. Looks good! Thank you for PR.
```
bkz@debian:~/rtw88$ make deb
debuild --no-lintian --lintian-hook "lintian --fail-on error,warning --suppress-tags bad-distribution-in-changes-file -- %p_%v_*.changes" --no-sign -b
 dpkg-buildpackage -us -uc -ui -b
dpkg-buildpackage: info: source package rtw88
dpkg-buildpackage: info: source version 5.12.0.5+git20231016.d193f2a-1
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by "Radxa Computer Co., Ltd" <[dev@radxa.com](mailto:dev@radxa.com)>
 dpkg-source --before-build .
dpkg-buildpackage: info: host architecture amd64
 fakeroot debian/rules clean
dh clean
   dh_auto_clean
make -j2 distclean
make[1]: Entering directory '/home/bkz/rtw88'
rm -rf ./SOURCE
rm -rf debian/.debhelper debian/rtw88-dkms debian/debhelper-build-stamp debian/files debian/*.debhelper.log debian/*.*.debhelper debian/*.substvars
make[1]: Leaving directory '/home/bkz/rtw88'
   dh_clean
 debian/rules build
dh build
   dh_update_autotools_config
   dh_autoreconf
   dh_auto_configure
   dh_auto_build
make -j2 "INSTALL=install --strip-program=true"
make[1]: Entering directory '/home/bkz/rtw88'
echo -e "git clone [https://github.com/radxa-pkg/rtw88.git\ngit](https://github.com/radxa-pkg/rtw88.git%5Cngit) checkout a5e56d9be0f4b1ac678d84a1c1373c2bdcd5d91e" > "SOURCE"
make[1]: Leaving directory '/home/bkz/rtw88'
   dh_auto_test
   create-stamp debian/debhelper-build-stamp
 fakeroot debian/rules binary
dh binary
   dh_testroot
   dh_prep
   dh_auto_install --destdir=debian/rtw88-dkms/
   debian/rules override_dh_install
make[1]: Entering directory '/home/bkz/rtw88'
dh_install -prtw88-dkms --exclude=sign-file src/* usr/src/rtw88-5.12.0.5+git20231016.d193f2a-1/
make[1]: Leaving directory '/home/bkz/rtw88'
   dh_installdocs
   dh_installchangelogs
   debian/rules override_dh_dkms
make[1]: Entering directory '/home/bkz/rtw88'
dh_dkms -V 5.12.0.5+git20231016.d193f2a-1
make[1]: Leaving directory '/home/bkz/rtw88'
   dh_lintian
   dh_perl
   dh_link
   dh_strip_nondeterminism
   dh_compress
   dh_fixperms
   dh_missing
   dh_installdeb
   dh_gencontrol
   dh_md5sums
   debian/rules override_dh_builddeb
make[1]: Entering directory '/home/bkz/rtw88'
dh_builddeb -- -Zxz
dpkg-deb: building package 'rtw88-dkms' in '../rtw88-dkms_5.12.0.5+git20231016.d193f2a-1_all.deb'.
make[1]: Leaving directory '/home/bkz/rtw88'
 dpkg-genbuildinfo --build=binary -O../rtw88_5.12.0.5+git20231016.d193f2a-1_amd64.buildinfo
 dpkg-genchanges --build=binary -O../rtw88_5.12.0.5+git20231016.d193f2a-1_amd64.changes
dpkg-genchanges: info: binary-only upload (no source code included)
 dpkg-source --after-build .
dpkg-buildpackage: info: binary-only upload (no source included)
 Running lintian-hook
 lintian --fail-on error,warning --suppress-tags bad-distribution-in-changes-file -- rtw88_5.12.0.5+git20231016.d193f2a-1_*.changes
 ```

**Pull request merged**
