### PR TITLE
Fixes small changes in Makefile(pr #211)

### PR DESCRIPTION
**Pull request by gtisan**
I didn't know how to change the commit history of pr #211 therefore
I created a new pull request to fix the problem with SDIO. 

You can delete old pr #211 or I can do it after review.

### CODE REVIEW

**Comment by dubhater** [comment]
It still doesn't work. :) I have ``CONFIG_PCI=y`` and ``CONFIG_USB=y``, but ``CONFIG_MMC=m``.

**Comment by a5a5aa555oo** [comment]
On ArchLinux/Debian ====> CONFIG_MMC=m
On Ubuntu/LinuxMint ====> CONFIG_MMC=y

so `ifneq ($(CONFIG_MMC), )` should be better.

**Comment by gtisan** [comment]
Thanks, I did it.

In this repo the firmware for 8822cu(rtw8822c_fw.bin) is older than in linux-firmware.
Is it fine or should we upgrade to the latest firmware ?

**Comment by dubhater** [comment]
We should upgrade the firmware.

**Comment by a5a5aa555oo** [comment]
I compared the firmware files here with the ones in linux-firmware, and the result is as below:
rtl8822cu_fw.bin: firmware for bt, older than the one in linux-firmware (0xFFB8_ABD3 vs AED6_6DCB)
rtw8723d_fw.bin: identical
rtw8812a_fw.bin: only exist in this repo
rtw8821a_fw.bin: identical
rtw8821c_fw.bin: older than the one in linux-firmware (v24.8 vs v24.11)
rtw8822b_fw.bin: identical
rtw8822c_fw.bin: older than the one in linux-firmware (v9.9.13 vs v9.9.15)
rtw8822c_wow_fw.bin: identical

I can upgrade them and put them in a folder called firmware together if you permitt.

**Comment by dubhater** [comment]
@a5a5aa555oo Sounds good to me. I think we can delete the Bluetooth firmware because this repository doesn't provide Bluetooth drivers.

**Comment by a5a5aa555oo** [comment]
@dubhater I think so,too. I will delete rtl8822cu_fw.bin and add/upgrade all the firmware rtw88 requires, thank you!~

**Comment by dubhater** [comment]
Merged, thank you!

**Comment by dubhater** [comment]
@gtisan Does this break the uninstall target? It tries to unload the SDIO modules, which maybe weren't compiled. If the module doesn't exist at all, modprobe -r fails and make aborts.

https://github.com/morrownr/8812au-20210820/issues/27#issuecomment-2246550487

**Pull request closed without merging**
